apps/pay_admins/urls.py
from django.urls import path, include
from .views import *


app_name = 'pay_admins'


urlpatterns = [
    path('services/create/', CreateService.as_view(), name='service-create'),
    path('faculties/create/', CreateFaculty.as_view(), name='faculty-create'),
    path('services/list/', ListServices.as_view(), name='service-list'),
    path('faculties/create/', CreateFaculty.as_view(), name='faculty-create'),
    # path('faculties/list/', ListFaculty.as_view(), name='faculty-list'),
    path('sub/create/', CreateSubAdmin.as_view(), name='create'),
    # path('payment/list/', ListPayments.as_view(), name='payments-list'),
    path('payment/verify/<token>/<status>/', Verify.as_view(), name='payment-verify'),
    path('payment/cancel/<token>/<status>/', Cancel.as_view(), name='payment-cancel'),
    path('payment/search/', search, name='payment-search'),
    path('settings/', UserList.as_view(), name='settings'),
    path('complaint/resolve/<id>/<status>/', Resolve.as_view(), name='resolve'),
    path('profile/<id>/', Profile.as_view(), name='profile'),
    path('sub/active/<code>/<status>/', ActiveAccount.as_view(), name='active'),
    path('sub/deactive/<code>/<status>/', DeActiveAccount.as_view(), name='deactive'),
    path('service/update/<id>/', EditService.as_view(), name='service-update'),
    path('', include('django.contrib.auth.urls')),
    # path('users/detail/<user_id>/', UserDetail.as_view(), name='users-detail'),
    path('users/<user_id>/', UserDetails.as_view(), name='user-detail'),
]

gtuc_pay_api/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

from apps.pay_admins import urls as admin_urls
from apps.users import urls as user_urls
from gtuc_pay_api import settings
from apps.pay import urls as pay_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('admins/', include(admin_urls, namespace='admins')),
    path('users/', include(user_urls, namespace='users')),
    path('pay/', include(pay_urls, namespace='pay')),
    path('', TemplateView.as_view(template_name='home.html'), name='home'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/users/models.py
from django.contrib.auth.base_user import BaseUserManager, AbstractBaseUser
from django.contrib.auth.models import PermissionsMixin
from django.utils.translation import gettext_lazy as _
from apps.utils.random_stuff import *
from django.db import models
# from django.db.models.signals import post_save
# from django.dispatch import receiver
# from ..utils.random_stuff import invite_new_user_email


# Create your models here.
class GPUserManager(BaseUserManager):
    def create_user(self, email, first_name, last_name, password=None, **extra_fields):
        if not email:
            raise ValueError('username is required')

        user = self.model(
            email=email,
            first_name=first_name,
            last_name=last_name,
        )
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, first_name, last_name, password):
        user = self.create_user(email=email, first_name=first_name, last_name=last_name, password=password)
        user.is_superuser = True
        user.is_active = True
        user.is_staff = True
        user.username = user.email
        user.save(using=self._db)
        return user


USER_TYPES = {
    ('SAU', 'Student App User'),
    ('ASU', 'Accounts Office Super User'),
    ('AOU', 'Accounts Office User'),
}


SEX = {
    ('male', 'male'),
    ('female', 'female'),
    ('other', 'other')
}


class GPUser(AbstractBaseUser, PermissionsMixin):
    user_id = models.CharField(unique=True, default=generate_id, editable=False, max_length=5)
    username = models.CharField(
        _('Username'),
        max_length=255,
        blank=True,
        null=True,
    )
    email = models.EmailField(
        _('Email address'),
        unique=True,
    )
    first_name = models.CharField(_('First Name'), max_length=255, blank=True, null=True)
    last_name = models.CharField(_('Last Name'), max_length=255, blank=True, null=True)
    title = models.CharField(_('Title'), max_length=255, blank=True, null=True)
    staff_id = models.CharField(_('Staff Id'), max_length=255, blank=True, null=True)
    user_profile = models.FileField(_('User Profile'), upload_to='media/', blank=True, null=True)
    gender = models.CharField(_('Gender'), choices=SEX, default='other', max_length=255, blank=True, null=True)
    student_id = models.CharField(_('Staff Id'), max_length=255, blank=True, null=True)
    is_active = models.BooleanField(_('Active Status'), default=True)
    is_staff = models.BooleanField(_('Staff Status'), default=False)
    is_superuser = models.BooleanField(_('Super User Status'), default=False)
    date_of_birth = models.DateField(_('Date of Birth'), default=timezone.now)
    login_number = models.IntegerField(_('Login Number'), default=0, blank=True, null=True)
    date_joined = models.DateTimeField(_('Date Joined'), default=timezone.now)
    user_type = models.CharField(_('User Type'), choices=USER_TYPES, max_length=255, default='SAU', blank=True, null=True)

    objects = GPUserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['first_name', 'last_name']

    def get_full_name(self):
        return f'{self.first_name} {self.last_name}'

    def get_short_name(self):
        return self.first_name

    def get_dob(self):
        return self.date_of_birth

    class Meta:
        verbose_name_plural = 'GTUC Pay Users'
        verbose_name = 'user'
        ordering = ('id', 'user_id', 'date_joined')

    def __str__(self):
        return f'{self.email}'


# def invite_user(sender, instance, created, **kwargs):
#     if created and instance.user_type == 'ASU' or instance.user_type == 'AOU':
#         invite_new_user_email(sender, instance.user_id)
#
#
# post_save.connect(invite_user, sender=settings.AUTH_USER_MODEL)

templates/admins/_password.html
{{ form.as_p }}

templates/admins/dashboard.html
{% extends 'admin_layout.html'  %}
{% load humanize %}
{% load static from staticfiles %}
{% block title %}Dashboard | {{ block.super }}{% endblock %}
{% block content %}
   <div class="row">
        <div class="col-lg-12">
            <div class="card">
                <div class="card-title data-table-list">
                    <div class="basic-tb-hd">
                        <h4>Students Payments </h4>
                    </div>

                </div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-6 col-sm-6 col-lg-5 right-aligned">
                            <div class="input-group input-group-rounded">
                                <input type="text" id="myInput" onkeyup="myFunction()" placeholder="Search for token..." name="Search" class="form-control">
                                <span class="input-group-btn small"><button class="btn btn-warning btn-group-right" type="submit"><i class="ti-search"></i></button></span>
                            </div>
                        </div>
                    </div>
                    <div class="table-responsive">
                        <table id="myTable" class="table table-hover">
                            <thead>
                                <tr>
                                    <th>Token</th>
                                    <th>Student Name</th>
                                    <th>Student Index</th>
                                    <th>Service</th>
                                    <th>Payment Option</th>
                                    <th>Amount</th>
                                    <th>Balance</th>
                                    <th>Date Paid</th>
                                    <th>Actions</th>
                                </tr>
                            </thead>
                            <tbody>
                            {% if object_list %}
                                {% for pay in object_list %}
                                    <tr>
                                        <td scope="row">{{ pay.token }}</td>
                                        <td>{{ pay.student_full_name }}</td>
                                        <td>{{ pay.student_id }}</td>
                                        <td>{{ pay.service_to_pay }}</td>

                                        {% if pay.pay_with == 'MTN' %}
                                            <td class="center"><span><img src="{% static 'images/mtnlogo.jpg' %}" height="40" width="60"></span></td>
                                        {% elif pay.pay_with == 'Voda' %}
                                            <td><span><img src="{% static 'images/vodalogo.jpg' %}" height="40" width="60"></span></td>
                                        {% elif pay.pay_with == 'Tigo' %}
                                            <td><span><img src="{% static 'images/tigologo.png' %}" height="40" width="60"></span></td>
                                        {% elif pay.pay_with == 'Air' %}
                                            <td><span><img src="{% static 'images/airtellogo.jpg' %}" height="40" width="60"></span></td>
                                        {% elif pay.is_card == True %}
                                            <td><span><img src="{% static 'images/card.png' %}" height="40" width="60"></span></td>
                                        {% endif %}

                                        <td>{{ pay.amount | intcomma }}</td>
                                        <td>{{ pay.balance | intcomma }}</td>
                                        <td>{{ pay.paid_at | naturaltime }}</td>
                                        <td class="color-primary">
                                            {% if not pay.is_verified %}
                                            <a href="{% url 'admins:payment-verify' pay.token 'verified' %}" class="btn btn-success">
                                                <span> Verify</span>
                                            </a>
                                            {% endif %}
{#                                            <a href="{% url 'admins:payment-cancel' pay.token 'cancel' %}" class="btn btn-danger">#}
{#                                                <span class="ti-close"></span>#}
{#                                            </a>#}
                                        </td>


                                    </tr>
                                {% endfor %}
                            {% else %}
                                This is no payment records
                            {% endif %}
                            </tbody>
                        </table>
                        <div align="right">
                    {% if is_paginated %}
                    <ul class="pagination">
                        {% if page_obj.has_previous %}
                            <li><a href="?page={{ page_obj.previous_page_number }}"><span class="btn btn-success ti ti-angle-double-left"></span></a></li>
                        {% else %}
                            <li class="disabled"><span class="btn btn-warning ti ti-angle-double-left"></span></li>
                        {% endif %}
                        {% for i in paginator.page_range %}
                            {% if page_obj.number == i %}
                                <li class="active"><span class="btn btn-outline-warning">{{ i }} <span class="sr-only">(current)</span></span></li>
                            {% else %}
                                <li><a href="?page={{ i }}"><span class="btn btn-success">{{ i }}</span></a></li>
                            {% endif %}
                        {% endfor %}
                        {% if page_obj.has_next %}
                            <li><a href="?page={{ page_obj.next_page_number }}"><span class="btn btn-success ti ti-angle-double-right"></span></a></li>
                        {% else %}
                            <li class="disabled"><span class="btn btn-warning ti ti-angle-double-right"></span></li>
                        {% endif %}
                    </ul>
                {% endif %}
                </div>
                    </div>
                </div>
            </div>
        </div>


   </div>
{% endblock %}
{% block js %}
    <script>
        function myFunction() {
          // Declare variables
          var input, filter, table, tr, td, i, txtValue;
          input = document.getElementById("myInput");
          filter = input.value.toUpperCase();
          table = document.getElementById("myTable");
          tr = table.getElementsByTagName("tr");

          // Loop through all table rows, and hide those who don't match the search query
          for (i = 0; i < tr.length; i++) {
            td = tr[i].getElementsByTagName("td")[0];
            if (td) {
              txtValue = td.textContent || td.innerText;
              if (txtValue.toUpperCase().indexOf(filter) > -1) {
                tr[i].style.display = "";
              } else {
                tr[i].style.display = "none";
              }
            }
          }
        }
    </script>
{% endblock %}

templates/admins/first_dash.html
{% load static from staticfiles %}
{% load bootstrap3 %}
{% load pay_tags %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Jekyll v3.8.5">
    <title>Cover Template · Bootstrap</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/4.3/examples/cover/">

    <!-- Bootstrap core CSS -->
<link href="{% static 'css/lib/bootstrap.min.css' %}" rel="stylesheet">


    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>
    <!-- Custom styles for this template -->
    <link href="{% static 'css/cover.css' %}" rel="stylesheet">
  </head>
  <body class="text-center">
    <div class="cover-container d-flex w-100 h-100 p-3 mx-auto flex-column">
  <header class="masthead mb-auto">
    <div class="inner">
      <h3 class="masthead-brand">GTUC Pay</h3>
      <nav class="nav nav-masthead justify-content-center">
        <a class="nav-link active" href="#">Home</a>
        <a class="nav-link" href="#">Features</a>
        <a class="nav-link" href="#">Contact</a>
      </nav>
    </div>
  </header>

  <main role="main" class="inner cover">
    <h1 class="cover-heading">Welcome to Ghana Technology University Payment System Administration Portal</h1>
    <p class="lead">Your account as {{ user.get_user_type_display }} permissions. Before you proceed to the dashboard, please change your password</p>
    <p class="lead">
        {% change_password %}
    </p>
  </main>

  <footer class="mastfoot mt-auto">
    <div class="inner">
      <p>Developed by Moon Projects</p>
    </div>
  </footer>
</div>
</body>
</html>

templates/admins/preference.html
{% extends 'admin_layout.html' %}
{% load static from staticfiles %}
{% block title %}Settings | {{ block.super }}{% endblock %}
{% load pay_tags %}
{% block content %}
    <div class="row">
        <div class="col-lg-8">
            <div class="card">
                <div class="card-title">
                    <h4>Admin Users</h4>

                </div>
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table">
                            <thead>
                                <tr>
                                    <th>Email</th>
                                    <th>Last Login</th>
                                    <th>Status</th>
                                    <th>Actions</th>
                                </tr>

                            </thead>
                            <tbody>
                                {% if admins %}
                                    {% for user in admins %}
                                        <tr>
                                            <td>{{ user.email }}</td>
                                            <td>{{ user.last_login }}</td>
                                            {% if user.is_active %}
                                                <td><span class="badge badge-success"><i class="ti-heart"></i></span></td>
                                            {% else %}
                                                <td><span class="badge badge-dark"><i class="ti-heart"></i></span></td>
                                            {% endif %}
                                            {% if user.is_active %}
                                                <td><a href="{% url 'admins:deactive' code=user.user_id status='deactive' %}" class="badge badge-danger"><span class="ti-power-off"></span></a></td>
                                            {% else %}
                                                <td><a href="{% url 'admins:active' code=user.user_id status='active' %}" class="badge badge-success"><span class="ti-power-off"></span></a></td>
                                            {% endif %}

                                        </tr>
                                    {% endfor %}
                                {% endif %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
        {% if user.user_type == 'ASU' %}
            <div class="col-lg-4 ">
                <div class="card">
                    <div class="card-title">Create Sub Admin</div>
                    <div class="card-body">
                        {% user_form %}
                    </div>
                </div>
            </div>
        {% endif %}
    </div>
    <div class="row">
        <div class="col-lg-4 col-md-9 col-sm-9">
            <div class="row">
                <div class="col-lg-12 col-md-12 col-sm-12">
                    <div class="card bg-primary">
                        <div class="weather-widget">
                            Users Complaints and Feedback
                        </div>
                    </div>
                </div>
                <div class="col-lg-12 col-md-12 col-sm-12">
                    <div class="card">
                        <div class="testimonial-widget-one">
                            <div class="testimonial-widget-one owl-carousel owl-theme">
                                {% if complaints %}
                                    {% for complaint in complaints %}
                                        <div class="item">
                                            <div class="testimonial-content">

                                                <div class="testimonial-text">
                                                    <i class="fa fa-quote-left"></i> {{ complaint.message }}
                                                    <i class="fa fa-quote-right"></i>
                                                </div>

                                                <div class="testimonial-author">{{ complaint.report_by.get_full_name }}</div>
                                                <div class="testimonial-author-position">{{ complaint.date_created }}</div>
                                                <img class="testimonial-author-img" src="{% if complaint.report_by.user_profile %}{{ complaint.report_by.user_profile.url }}{% else %}{% static 'images/avatar/1.jpg' %}{% endif %}" alt="" />
                                                {% if not complaint.is_resolve %}
                                                    <div align="left"><a href="{% url 'admins:resolve' id=complaint.id status='resolved' %}" class="badge badge-success"><span class="ti ti-check"></span></a> </div>
                                                {% endif %}
                                            </div>
                                        </div>
                                    {% endfor %}
                                {% endif %}

                            </div>
                        </div>
                    </div>

                </div>
            </div>
            <div class="row">
                <div class="col-lg-12 col-sm-12 col-md-12">
                    <div class="card">
                        <div class="header-title">Create A Faculty</div><br><br>
                        <div class="form-group">
                            {% faculty_form %}
                        </div>

                    </div>
                </div>
            </div>
        </div>
        <!-- /# column -->
        <div class="col-lg-8">
            <div class="card">
                <div class="card-title pr">
                    <h4>Web Users</h4>

                </div>
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table student-data-table m-t-20">
                            <thead>
                                <tr>
                                    <th>Full Name</th>
                                    <th>Status</th>
                                    <th>Email</th>
                                    <th>Actions</th>

                                </tr>
                            </thead>
                            <tbody>
                            {% if app_users %}
                                {% for user in app_users %}
                                    <tr>
                                        <td>{{ user.get_full_name }}</td>
                                        <td>{% if user.is_active %}<span class="ti ti-check"></span>{% else %}<span class="ti ti-close"></span>{% endif %}</td>
                                        <td>
                                            {{ user.email }}
                                        </td>
                                        <td>
                                           <a href="{% url 'admins:user-detail' user.user_id %}"><span class="ti ti-eye"></span></a>
                                        </td>


                                    </tr>
                                {% endfor %}
                            {% else %}
                                Nothing to show
                            {% endif %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
        <!-- /# column -->
    </div>
{% endblock %}

templates/admins/service_update.html
{% extends 'admin_layout.html' %}
{% load static from staticfiles %}
{% block title %}Update {{ object.service_name }} | {{ block.super }}{% endblock %}
{% block content %}
    <div class="row">
            <div class="col-lg-12">
              <div class="card">
                <div class="card-body">
                  <div class="user-profile">
                    <div class="row">
                      <div class="col-lg-4">
                        <div class="user-photo m-b-30">
                          <img class="img-fluid" src="{% if not object.logo %}{% static 'images/Picture1.png' %}{% else %}{{ object.logo.url }}{% endif %}" style="border-radius: 10px" alt="" />
                        </div>
                      </div>
                      <div class="col-lg-8">
                        <div class="user-profile-name">{{ object.service_name }}</div>
                        <div class="user-Location">
                          <i class="ti-key"></i> {{ object.account_number }}
                        </div>
                        <div class="user-job-title">{{ object.amount }}</div>
                        <div class="custom-tab user-profile-tab">
                          <ul class="nav nav-tabs" role="tablist">
                            <li role="presentation" class="active">
                              <a href="#1" aria-controls="1" role="tab" data-toggle="tab">Edit {{ object.service_name }}</a>
                            </li>
                          </ul>
                          <div class="tab-content">
                            <div role="tabpanel" class="tab-pane active" id="1">
                              <div class="contact-information">
                                <form action="{% url 'admins:service-update' object.id %}" method="post" enctype='multipart/form-data'>
                                    {% csrf_token %}
                                    <div class="form-group">
                                      <label class="contact-title">Service Name:</label>
                                      <input type="text" class="form-control input-rounded" name="{{ form.service_name.name }}" value="{{ form.service_name.value }}" />
                                    </div>
                                    <div class="form-group">
                                      <label class="contact-title">Account Number:</label>
                                      <input type="text" class="form-control input-rounded" name="{{ form.account_number.name }}" value="{{ form.account_number.value }}" />
                                    </div>
                                    <div class="form-group">
                                      <label class="contact-title">Bank Name:</label>
                                      <input type="text" class="form-control input-rounded" name="{{ form.bank_name.name }}" value="{{ form.bank_name.value }}" />
                                    </div>
                                    <div class="form-group">
                                      <label class="contact-title">Currency:</label>
                                      <select class="form-control input-rounded" name="{{ form.currency.name }}">
                                          {% for x,y in form.fields.currency.choices %}
                                            <option value="{{ x }}" {% if form.currency.value == x %} selected {% endif %}>{{ y }}</option>
                                          {% endfor %}
                                      </select>
                                    </div>
                                    <div class="form-group">
                                      <label class="contact-title">Amount:</label>
                                      <input type="number" class="form-control input-rounded" name="{{ form.amount.name }}" value="{{ form.amount.value }}" />
                                    </div>
                                    <div class="form-group">
                                      <label class="contact-title">Logo:</label>
                                      <input type="file" name="{{ form.logo.name }}" value="{{ form.logo.url }}" />
                                    </div>
                                    <input type="submit" class="btn btn-success" value="Save">
                                </form>
                              </div>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
{% endblock %}

templates/admins/services_list.html
{% extends 'admin_layout.html' %}
{% load static from staticfiles %}
{% load pay_tags %}
{% block title %}Services | {{ block.super }}{% endblock %}
{% block content %}

    <div class="row">
        {% if object_list %}
            {% for service in object_list %}
                <div class="col-lg-3 col-sm-6 col-md-6">
                    <div class="card">
                        <div align="right">
                            <span class="dropup"></span><a href="#" class="ti-more-alt dropdown" data-toggle="dropdown"></a>
                            <ul class="dropdown-menu">
                                <!--<li class="dropdown-header">Options</li>-->
                                <li><a href="{% url 'admins:service-update' service.id %}">Edit</a></li>
                                <li class="sweetalert"><a href="#" class="sweet-confirm">Delete</a></li>
                            </ul>
                        </div>

                        <div class="stat-widget-one">
                            {% if service.logo %}
                                <div class="stat-icon dib"><img src="{{ service.logo.url }}" height="60" width="60" border="1" /> </div>
                            {% else %}
                                <div class="stat-icon dib"><img src="{% static 'images/default.png' %}" height="60" width="60" border="1" /> </div>
                            {% endif %}
                            <div class="stat-content dib">
                                <div class="stat-text">{{ service.service_name }}</div>
                                <div class="stat-digit" style="font-size: 17px;">{{ service.currency }} {{ service.amount }}</div>
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
        {% endif %}
        <div class="col-lg-3">
            <a href="#" data-toggle="modal" data-target="#addService">
                <div class="card">
                    <div class="stat-widget-one">
                        <div class="stat-icon dib"><i class="ti-new-window color-primary border-primary"></i></div>
                        <div class="stat-content dib">
                            <div class="stat-text center-align">Click to add new</div>

                        </div>
                    </div>
                </div>
            </a>

        </div>
    </div>
    <!-- Modal -->
<div class="modal fade l" id="addService" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLongTitle">Add Service</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        {% service_form %}
      </div>
    </div>
  </div>
</div>
{% endblock %}

templates/admins/users-details.html
{% extends 'admin_layout.html' %}
{% block content %}
    {{ user_object.get_full_name }}
{% endblock %}