apps/pay/urls.py
from django.urls import *
from .views import *

app_name = 'pay'


urlpatterns = [
    path('service/detail/<id>/', ServiceDetail.as_view(), name='service-detail'),
    path('momo/<id>/', PayMomo.as_view(), name='pay-momo'),
    path('card/<id>/', PayCard.as_view(), name='pay-card'),
    path('momo/confirm/<id>/', ConfirmMomoPay.as_view(), name='confirm-momo'),
    path('card/confirm/<id>/', ConfirmCardPay.as_view(), name='confirm-card'),
    path('cancel/<id>/', CancelPayment.as_view(), name='cancel'),
    path('success/<id>/', SuccessPayment.as_view(), name='success'),
    path('transactions/', UserPayment.as_view(), name='transactions'),
    path('transaction/detail/<id>/', PaymentDetail.as_view(), name='transaction-detail'),
    path('support/', Support.as_view(), name='support'),
]

apps/pay_admins/urls.py
from django.urls import path, include
from .views import *


app_name = 'pay_admins'


urlpatterns = [
    path('services/create/', CreateService.as_view(), name='service-create'),
    path('faculties/create/', CreateFaculty.as_view(), name='faculty-create'),
    path('services/list/', ListServices.as_view(), name='service-list'),
    path('faculties/create/', CreateFaculty.as_view(), name='faculty-create'),
    # path('faculties/list/', ListFaculty.as_view(), name='faculty-list'),
    path('sub/create/', CreateSubAdmin.as_view(), name='create'),
    # path('payment/list/', ListPayments.as_view(), name='payments-list'),
    path('payment/verify/<token>/<status>/', Verify.as_view(), name='payment-verify'),
    path('payment/cancel/<token>/<status>/', Cancel.as_view(), name='payment-cancel'),
    path('payment/search/', search, name='payment-search'),
    path('settings/', UserList.as_view(), name='settings'),
    path('complaint/resolve/<id>/<status>/', Resolve.as_view(), name='resolve'),
    path('profile/<id>/', Profile.as_view(), name='profile'),
    path('sub/active/<code>/<status>/', ActiveAccount.as_view(), name='active'),
    path('sub/deactive/<code>/<status>/', DeActiveAccount.as_view(), name='deactive'),
    path('service/update/<id>/', EditService.as_view(), name='service-update'),
    path('', include('django.contrib.auth.urls')),
    # path('users/detail/<user_id>/', UserDetail.as_view(), name='users-detail'),
    path('users/<user_id>/', UserDetails.as_view(), name='user-detail'),
]

apps/users/urls.py
from django.urls import path, include
from django.views.generic import TemplateView

from apps.users.views import *

app_name = 'users'


urlpatterns = [
    path('dashboard/', Dashboard.as_view(), name='dashboard'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('signup/', SignUpView.as_view(), name='signup'),
    # path('layout/admin/', TemplateView.as_view(template_name='admin_layout.html')),
    path('password/', ChangePassword.as_view(), name='password'),
    path('profile/<id>', Profile.as_view(), name='profile'),
    path('', include('django.contrib.auth.urls')),



]

gtuc_pay_api/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

from apps.pay_admins import urls as admin_urls
from apps.users import urls as user_urls
from gtuc_pay_api import settings
from apps.pay import urls as pay_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('admins/', include(admin_urls, namespace='admins')),
    path('users/', include(user_urls, namespace='users')),
    path('pay/', include(pay_urls, namespace='pay')),
    path('', TemplateView.as_view(template_name='home.html'), name='home'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/users/models.py
from django.contrib.auth.base_user import BaseUserManager, AbstractBaseUser
from django.contrib.auth.models import PermissionsMixin
from django.utils.translation import gettext_lazy as _
from apps.utils.random_stuff import *
from django.db import models
# from django.db.models.signals import post_save
# from django.dispatch import receiver
# from ..utils.random_stuff import invite_new_user_email


# Create your models here.
class GPUserManager(BaseUserManager):
    def create_user(self, email, first_name, last_name, password=None, **extra_fields):
        if not email:
            raise ValueError('username is required')

        user = self.model(
            email=email,
            first_name=first_name,
            last_name=last_name,
        )
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, first_name, last_name, password):
        user = self.create_user(email=email, first_name=first_name, last_name=last_name, password=password)
        user.is_superuser = True
        user.is_active = True
        user.is_staff = True
        user.username = user.email
        user.save(using=self._db)
        return user


USER_TYPES = {
    ('SAU', 'Student App User'),
    ('ASU', 'Accounts Office Super User'),
    ('AOU', 'Accounts Office User'),
}


SEX = {
    ('male', 'male'),
    ('female', 'female'),
    ('other', 'other')
}


class GPUser(AbstractBaseUser, PermissionsMixin):
    user_id = models.CharField(unique=True, default=generate_id, editable=False, max_length=5)
    username = models.CharField(
        _('Username'),
        max_length=255,
        blank=True,
        null=True,
    )
    email = models.EmailField(
        _('Email address'),
        unique=True,
    )
    first_name = models.CharField(_('First Name'), max_length=255, blank=True, null=True)
    last_name = models.CharField(_('Last Name'), max_length=255, blank=True, null=True)
    title = models.CharField(_('Title'), max_length=255, blank=True, null=True)
    staff_id = models.CharField(_('Staff Id'), max_length=255, blank=True, null=True)
    user_profile = models.FileField(_('User Profile'), upload_to='media/', blank=True, null=True)
    gender = models.CharField(_('Gender'), choices=SEX, default='other', max_length=255, blank=True, null=True)
    student_id = models.CharField(_('Staff Id'), max_length=255, blank=True, null=True)
    is_active = models.BooleanField(_('Active Status'), default=True)
    is_staff = models.BooleanField(_('Staff Status'), default=False)
    is_superuser = models.BooleanField(_('Super User Status'), default=False)
    date_of_birth = models.DateField(_('Date of Birth'), default=timezone.now)
    login_number = models.IntegerField(_('Login Number'), default=0, blank=True, null=True)
    date_joined = models.DateTimeField(_('Date Joined'), default=timezone.now)
    user_type = models.CharField(_('User Type'), choices=USER_TYPES, max_length=255, default='SAU', blank=True, null=True)

    objects = GPUserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['first_name', 'last_name']

    def get_full_name(self):
        return f'{self.first_name} {self.last_name}'

    def get_short_name(self):
        return self.first_name

    def get_dob(self):
        return self.date_of_birth

    class Meta:
        verbose_name_plural = 'GTUC Pay Users'
        verbose_name = 'user'
        ordering = ('id', 'user_id', 'date_joined')

    def __str__(self):
        return f'{self.email}'


# def invite_user(sender, instance, created, **kwargs):
#     if created and instance.user_type == 'ASU' or instance.user_type == 'AOU':
#         invite_new_user_email(sender, instance.user_id)
#
#
# post_save.connect(invite_user, sender=settings.AUTH_USER_MODEL)

templates/admin_layout.html
{% load static from staticfiles %}
{% if user.user_type == 'AOU' or user.user_type == 'ASU' %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>{% block title %}GTUC Pay Admin{% endblock %}</title>

    <!-- ================= Favicon ================== -->
    <!-- Standard -->
    <link rel="shortcut icon" href="{% static 'images/Picture1.png' %}">
    <!-- Retina iPad Touch Icon-->
    <link rel="apple-touch-icon" sizes="144x144" href="{% static 'images/Picture1.png' %}">
    <!-- Retina iPhone Touch Icon-->
    <link rel="apple-touch-icon" sizes="114x114" href="{% static 'images/Picture1.png' %}">
    <!-- Standard iPad Touch Icon-->
    <link rel="apple-touch-icon" sizes="72x72" href="{% static 'images/Picture1.png' %}">
    <!-- Standard iPhone Touch Icon-->
    <link rel="apple-touch-icon" sizes="57x57" href="{% static 'images/Picture1.png' %}">

    <!-- Styles -->
    <link href="{% static 'css/lib/owl.carousel.min.css' %}" rel="stylesheet" />
    <link href="{% static 'css/lib/owl.theme.default.min.css' %}" rel="stylesheet" />
    <link href="{% static 'css/lib/weather-icons.css' %}" rel="stylesheet" />
    <link href="{% static 'css/lib/font-awesome.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/lib/themify-icons.css' %}" rel="stylesheet">
    <link href="{% static 'css/lib/menubar/sidebar.css' %}" rel="stylesheet">
    <link href="{% static 'css/lib/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/lib/helper.css' %}" rel="stylesheet">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    <link href="{% static 'css/jquery.dataTables.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/lib/sweetalert/sweetalert.css' %}" rel="stylesheet">
    <script src="{% static 'js/scripts.js' %}"></script>
</head>

<body>

    <div class="sidebar sidebar-hide-to-small sidebar-shrink sidebar-gestures">
        <div class="nano">
            <div class="nano-content">
                <div class="logo"><a href="{% url 'users:dashboard' %}"><img src="{% static 'images/Picture1.png' %}" width="65" height="60" alt="" /><span>GTUC Pay</span></a></div>
                <ul>
                    <li><a href="{% url 'users:dashboard' %}"><i class="ti-money"></i> Payments </a></li>
                    <li><a href="{% url 'admins:service-list' %}"><i class="ti-rss-alt"></i> Services</a></li>
                    <li><a href="{% url 'users:profile' user.id %}"><i class="ti-user"></i> Profile</a></li>
                    <li><a href="{% url 'admins:settings' %}"><i class="ti-layout-grid2-alt"></i> Settings</a></li>
                </ul>
            </div>
        </div>
    </div>
    <div class="header">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-12">
                    <div class="float-left">
                        <div class="hamburger sidebar-toggle">
                            <span class="line"></span>
                            <span class="line"></span>
                            <span class="line"></span>
                        </div>
                    </div>
                    <div class="float-right">
                        <div class="dib">
                            <div class="header-icon">
                                <a href="{% url 'users:profile' user.id %}" title="Click to view user profile" class="user-avatar">{{ user.get_short_name }}
                                    <img src="{% if user.user_profile %}{{ user.user_profile.url }}{% else %}{% static 'images/Picture1.png' %}{% endif %}" width="40" height="40" style="border-radius: 100px; border: 2px" class=user-photo" />
                                </a>
                                &nbsp;&nbsp;&nbsp;
                                <a href="{% url 'users:logout' %}" title="Click to logout" class="user-avatar">
                                    <i class=" ti-power-off"></i>
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="content-wrap">
        <div class="main">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-lg-8 p-r-0 title-margin-right">
                        <div class="page-header">
                            <div class="page-title">
                                <h1>Hello {{ user.get_full_name }} ({{ user.get_user_type_display }}) , <span>Welcome to GTUC Pay Admin Portal</span></h1>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- /# row -->
                <section id="main-content">
                    {% block content %}
                    {% endblock %}

                </section>
            </div>
        </div>
    </div>
    {% block js %}{% endblock %}
    <!-- jquery vendor -->
    <script src="{% static 'js/lib/jquery.min.js' %}"></script>
    <script src="{% static 'js/lib/jquery.nanoscroller.min.js' %}"></script>
    <!-- nano scroller -->
    <script src="{% static 'js/lib/menubar/sidebar.js' %}"></script>
    <script src="{% static 'js/lib/preloader/pace.min.js' %}"></script>
    <!-- sidebar -->
    
    <!-- bootstrap -->
    <script src="{% static 'js/lib/bootstrap.min.js' %}"></script><script src="{% static 'js/scripts.js' %}"></script>
    <!-- scripit init-->
    <script src="{% static 'js/lib/weather/jquery.simpleWeather.min.js' %}"></script>
    <script src="{% static 'js/lib/weather/weather-init.js' %}"></script>
    <script src="{% static 'js/lib/circle-progress/circle-progress.min.js' %}"></script>
    <script src="{% static 'js/lib/circle-progress/circle-progress-init.js' %}"></script>
    <script src="{% static 'js/lib/chartist/chartist.min.js' %}"></script>
    <script src="{% static 'js/lib/sparklinechart/jquery.sparkline.min.js' %}"></script>
    <script src="{% static 'js/lib/sparklinechart/sparkline.init.js' %}"></script>
    <script src="{% static 'js/lib/owl-carousel/owl.carousel.min.js' %}"></script>
    <script src="{% static 'js/lib/owl-carousel/owl.carousel-init.js' %}"></script>
    <script src="{% static 'js/lib/sweetalert/sweetalert.init.js' %}"></script>
    <script src="{% static 'js/lib/sweetalert/sweetalert.min.js' %}"></script>
    <script src="{% static 'js/lib/calendar-2/moment.latest.min.js' %}"></script>
    <script src="{% static 'js/lib/calendar-2/pignose.calendar.min.js' %}"></script>
    <script src="{% static 'js/lib/calendar-2/pignose.init.js' %}"></script>
    <script src="{% static 'js/data-table/data-table-act.js' %}"></script>
    <script src="{% static 'js/data-table/jquery.dataTables.min.js' %}"></script>

    <script src="{% static 'js/scripts.js' %}"></script>
    <script src="{% static 'js/dashboard2.js' %}"></script>


</body>

</html>
{% else %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Jekyll v3.8.5">
    <title>Error</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/4.3/examples/cover/">

    <!-- Bootstrap core CSS -->
<link href="{% static 'css/lib/bootstrap.min.css' %}" rel="stylesheet">


    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>
    <!-- Custom styles for this template -->
    <link href="{% static 'css/cover.css' %}" rel="stylesheet">
  </head>
  <body class="text-center">
    <div class="cover-container d-flex w-100 h-100 p-3 mx-auto flex-column">
  <header class="masthead mb-auto">
    <div class="inner">
      <h3 class="masthead-brand center"><img src="{% static 'images/Picture1.png' %}" height="90" width="100"> GTUC Pay</h3>
{#      <nav class="nav nav-masthead justify-content-center">#}
{#        <a class="nav-link active" href="#">Home</a>#}
{#        <a class="nav-link" href="#">Features</a>#}
{#        <a class="nav-link" href="#">Contact</a>#}
{#      </nav>#}
    </div>
  </header>

  <main role="main" class="inner cover">
    <h1 class="cover-heading">Oops...</h1>
    <p class="lead">Hi {{ user.get_full_name }}, {{ user.get_user_type_display }}, You are trying to access a page you are not allowed to view.</p>
    <p class="lead">
    <a href="{% url 'users:dashboard' %}" class="btn btn-compose">Go Back to Your Dashboard</a>
    </p>
  </main>

  <footer class="mastfoot mt-auto">
    <div class="inner">
      <p>Developed by <img src="{% static 'images/default.png' %}" width="20" height="20"> Moon Projects</p>
    </div>
  </footer>
</div>
</body>
</html>

{% endif %}

templates/home.html
{% load static from staticfiles %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Jekyll v3.8.5">
    <title>GTUC Pay</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/4.3/examples/cover/">

    <!-- Bootstrap core CSS -->
<link href="{% static 'css/lib/bootstrap.min.css' %}" rel="stylesheet">


    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>
    <!-- Custom styles for this template -->
    <link href="{% static 'css/cover.css' %}" rel="stylesheet">
  </head>
  <body style="background: linear-gradient(rgba(176,231,10,0.45), rgba(255, 0, 0, 0.45)), url({% static 'images/bgimg.JPG' %}) no-repeat; width: 100%; height: 100%;" class="text-center" >
    <div class="cover-container d-flex w-100 h-100 p-3 mx-auto flex-column">
  <header class="masthead mb-auto">
    <div class="inner">
      <h3 class="masthead-brand center"><img src="{% static 'images/Picture1.png' %}" height="90" width="100"> GTUC Pay</h3>
{#      <nav class="nav nav-masthead justify-content-center">#}
{#        <a class="nav-link active" href="#">Home</a>#}
{#        <a class="nav-link" href="#">Features</a>#}
{#        <a class="nav-link" href="#">Contact</a>#}
{#      </nav>#}
    </div>
  </header>

  <main role="main" class="inner cover">
    <h1 class="cover-heading">Let's get you started...</h1>
    <p class="lead">GTUC Pay is a platform for students and their sponsors to pay for all their university fees with ease. No hustle, no stress. Get your groove on!</p>
    <p class="lead">
    <a href="{% url 'users:login' %}" class="btn btn-dark">Login</a>&nbsp;&nbsp;<a href="{% url 'users:signup' %}" class="btn btn-dark">Join us</a>
    </p>
  </main>

  <footer class="mastfoot mt-auto">
    <div class="inner">
      <p>Developed by <img src="{% static 'images/default.png' %}" width="20" height="20"> Moon Projects</p>
    </div>
  </footer>
</div>
</body>
</html>

templates/layout.html
{% load static from staticfiles %}
{% if user.user_type == 'SAU' %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>{% block title %}GTUC Pay{% endblock %}</title>

    <!-- ================= Favicon ================== -->
    <!-- Standard -->
    <link rel="shortcut icon" href="{% static 'images/Picture1.png' %}">
    <!-- Retina iPad Touch Icon-->
    <link rel="apple-touch-icon" sizes="144x144" href="{% static 'images/Picture1.png' %}">
    <!-- Retina iPhone Touch Icon-->
    <link rel="apple-touch-icon" sizes="114x114" href="{% static 'images/Picture1.png' %}">
    <!-- Standard iPad Touch Icon-->
    <link rel="apple-touch-icon" sizes="72x72" href="{% static 'images/Picture1.png' %}">
    <!-- Standard iPhone Touch Icon-->
    <link rel="apple-touch-icon" sizes="57x57" href="{% static 'images/Picture1.png' %}">

    <!-- Styles -->
    <link href="{% static 'css/lib/owl.carousel.min.css' %}" rel="stylesheet" />
    <link href="{% static 'css/lib/owl.theme.default.min.css' %}" rel="stylesheet" />
    <link href="{% static 'css/lib/weather-icons.css' %}" rel="stylesheet" />
    <link href="{% static 'css/lib/font-awesome.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/lib/themify-icons.css' %}" rel="stylesheet">
    <link href="{% static 'css/lib/menubar/sidebar.css' %}" rel="stylesheet">
    <link href="{% static 'css/lib/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/lib/helper.css' %}" rel="stylesheet">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    <link href="{% static 'css/jquery.dataTables.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/lib/sweetalert/sweetalert.css' %}" rel="stylesheet">

    {% block css %}{% endblock %}
    <script src="{% static 'js/scripts.js' %}"></script>
    <style>
        @media (max-width: 767px) {
            .styleName {
                display:none;
            }
        }
    </style>
</head>

<body bgcolor="#f8f8ff">
    <div class="header" style="margin-left: auto; background-color: #282a67; height: auto">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-12">
                    <div class="float-left">
                        <div class="page-title" style="margin-left: 20px; margin-top: 20px;">
                            <h3 style="color: #ffffff;">{% block header %}STUDENT LAYOUT {% endblock %}</h3>

                        </div>
                    </div>
                    <div class="float-right">
                        <div class="dib">
                            <div class="header-icon">
                                <a href="{% url 'pay:transactions' %}" title="Click to view your transactions">
                                    <span class="ti-timer"></span>
                                </a>
                                &nbsp;&nbsp;
                                <a href="{% url 'users:profile' user.id %}" title="Click to view user profile" class="user-avatar">{{ user.get_short_name }}
                                    <img src="{% if user.user_profile %}{{ user.user_profile.url }}{% else %}{% static 'images/profile.png' %}{% endif %}" width="40" height="40" style="border-radius: 100px; border: 2px" class=user-photo" />
                                </a>
                                &nbsp;&nbsp;&nbsp;
                                <a href="{% url 'users:logout' %}" title="Click to logout" class="user-avatar">
                                    <i class=" ti-power-off"></i>
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="content-wrap">
        <div class="main">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-lg-8 col-sm-9">
                        <div class="page-header">
                            <div class="page-title">
                                <h1>Hello {{ user.get_full_name }}, <span>Pay your fees with ease. Click <a href="{% url 'pay:support' %}"><span class="ti ti-light-bulb"></span></a> for support</span></h1>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-4 col-sm-3" align="right">
                        <div class="page-header">
                            <div class="page-title">

                                    <li class="breadcrumb-item"><a href="{% url 'users:dashboard' %}"><span class="ti ti-home"></span> Dashboard</a></li>


                            </div>
                        </div>
                    </div>
                </div>
                <!-- /# row -->
                <section id="main-content">
                    {% block content %}
                    {% endblock %}

                </section>
            </div>
        </div>
    </div>

    <!-- jquery vendor -->
    <script src="{% static 'js/lib/jquery.min.js' %}"></script>
    <script src="{% static 'js/lib/jquery.nanoscroller.min.js' %}"></script>
    <!-- nano scroller -->
    <script src="{% static 'js/lib/menubar/sidebar.js' %}"></script>
    <script src="{% static 'js/lib/preloader/pace.min.js' %}"></script>
    <!-- sidebar -->

    <!-- bootstrap -->
    <script src="{% static 'js/lib/bootstrap.min.js' %}"></script><script src="{% static 'js/scripts.js' %}"></script>
    <!-- scripit init-->
    <script src="{% static 'js/lib/weather/jquery.simpleWeather.min.js' %}"></script>
    <script src="{% static 'js/lib/weather/weather-init.js' %}"></script>
    <script src="{% static 'js/lib/circle-progress/circle-progress.min.js' %}"></script>
    <script src="{% static 'js/lib/circle-progress/circle-progress-init.js' %}"></script>
    <script src="{% static 'js/lib/chartist/chartist.min.js' %}"></script>
    <script src="{% static 'js/lib/sparklinechart/jquery.sparkline.min.js' %}"></script>
    <script src="{% static 'js/lib/sparklinechart/sparkline.init.js' %}"></script>
    <script src="{% static 'js/lib/owl-carousel/owl.carousel.min.js' %}"></script>
    <script src="{% static 'js/lib/owl-carousel/owl.carousel-init.js' %}"></script>
    <script src="{% static 'js/lib/sweetalert/sweetalert.init.js' %}"></script>
    <script src="{% static 'js/lib/sweetalert/sweetalert.min.js' %}"></script>
    <script src="{% static 'js/lib/calendar-2/moment.latest.min.js' %}"></script>
    <script src="{% static 'js/lib/calendar-2/pignose.calendar.min.js' %}"></script>
    <script src="{% static 'js/lib/calendar-2/pignose.init.js' %}"></script>
    <script src="{% static 'js/data-table/data-table-act.js' %}"></script>
    <script src="{% static 'js/data-table/jquery.dataTables.min.js' %}"></script>

    <script src="{% static 'js/scripts.js' %}"></script>
    <script src="{% static 'js/dashboard2.js' %}"></script>
    <script src="{% static 'js/numberToWords.min.js' %}"></script>
    <script type="text/javascript">
        console.log("Hello");

    </script>
    {% block js %}{% endblock %}

</body>

</html>
{% else %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Jekyll v3.8.5">
    <title>Error</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/4.3/examples/cover/">

    <!-- Bootstrap core CSS -->
<link href="{% static 'css/lib/bootstrap.min.css' %}" rel="stylesheet">


    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>
    <!-- Custom styles for this template -->
    <link href="{% static 'css/cover.css' %}" rel="stylesheet">
  </head>
  <body class="text-center">
    <div class="cover-container d-flex w-100 h-100 p-3 mx-auto flex-column">
  <header class="masthead mb-auto">
    <div class="inner">
      <h3 class="masthead-brand center"><img src="{% static 'images/Picture1.png' %}" height="90" width="100"> GTUC Pay</h3>
{#      <nav class="nav nav-masthead justify-content-center">#}
{#        <a class="nav-link active" href="#">Home</a>#}
{#        <a class="nav-link" href="#">Features</a>#}
{#        <a class="nav-link" href="#">Contact</a>#}
{#      </nav>#}
    </div>
  </header>

  <main role="main" class="inner cover">
    <h1 class="cover-heading">Oops...</h1>
    <p class="lead">Hi {{ user.get_full_name }}, {{ user.get_user_type_display }}, You are trying to access a page you are not allowed to view.</p>
    <p class="lead">
    <a href="{% url 'users:dashboard' %}" class="btn btn-compose">Go Back to Your Dashboard</a>
    </p>
  </main>

  <footer class="mastfoot mt-auto">
    <div class="inner">
      <p>Developed by <img src="{% static 'images/default.png' %}" width="20" height="20"> Moon Projects</p>
    </div>
  </footer>
</div>
</body>
</html>

{% endif %}