apps/pay/urls.py
from django.urls import *
from .views import *

app_name = 'pay'


urlpatterns = [
    path('service/detail/<id>/', ServiceDetail.as_view(), name='service-detail'),
    path('momo/<id>/', PayMomo.as_view(), name='pay-momo'),
    path('card/<id>/', PayCard.as_view(), name='pay-card'),
    path('momo/confirm/<id>/', ConfirmMomoPay.as_view(), name='confirm-momo'),
    path('card/confirm/<id>/', ConfirmCardPay.as_view(), name='confirm-card'),
    path('cancel/<id>/', CancelPayment.as_view(), name='cancel'),
    path('success/<id>/', SuccessPayment.as_view(), name='success'),
    path('transactions/', UserPayment.as_view(), name='transactions'),
    path('transaction/detail/<id>/', PaymentDetail.as_view(), name='transaction-detail'),
    path('support/', Support.as_view(), name='support'),
]

apps/pay_admins/urls.py
from django.urls import path, include
from .views import *


app_name = 'pay_admins'


urlpatterns = [
    path('services/create/', CreateService.as_view(), name='service-create'),
    path('faculties/create/', CreateFaculty.as_view(), name='faculty-create'),
    path('services/list/', ListServices.as_view(), name='service-list'),
    path('faculties/create/', CreateFaculty.as_view(), name='faculty-create'),
    # path('faculties/list/', ListFaculty.as_view(), name='faculty-list'),
    path('sub/create/', CreateSubAdmin.as_view(), name='create'),
    # path('payment/list/', ListPayments.as_view(), name='payments-list'),
    path('payment/verify/<token>/<status>/', Verify.as_view(), name='payment-verify'),
    path('payment/cancel/<token>/<status>/', Cancel.as_view(), name='payment-cancel'),
    path('payment/search/', search, name='payment-search'),
    path('settings/', UserList.as_view(), name='settings'),
    path('complaint/resolve/<id>/<status>/', Resolve.as_view(), name='resolve'),
    path('profile/<id>/', Profile.as_view(), name='profile'),
    path('sub/active/<code>/<status>/', ActiveAccount.as_view(), name='active'),
    path('sub/deactive/<code>/<status>/', DeActiveAccount.as_view(), name='deactive'),
    path('service/update/<id>/', EditService.as_view(), name='service-update'),
    path('', include('django.contrib.auth.urls')),
    # path('users/detail/<user_id>/', UserDetail.as_view(), name='users-detail'),
    path('users/<user_id>/', UserDetails.as_view(), name='user-detail'),
]

apps/users/urls.py
from django.urls import path, include
from django.views.generic import TemplateView

from apps.users.views import *

app_name = 'users'


urlpatterns = [
    path('dashboard/', Dashboard.as_view(), name='dashboard'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('signup/', SignUpView.as_view(), name='signup'),
    # path('layout/admin/', TemplateView.as_view(template_name='admin_layout.html')),
    path('password/', ChangePassword.as_view(), name='password'),
    path('profile/<id>', Profile.as_view(), name='profile'),
    path('', include('django.contrib.auth.urls')),



]

gtuc_pay_api/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

from apps.pay_admins import urls as admin_urls
from apps.users import urls as user_urls
from gtuc_pay_api import settings
from apps.pay import urls as pay_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('admins/', include(admin_urls, namespace='admins')),
    path('users/', include(user_urls, namespace='users')),
    path('pay/', include(pay_urls, namespace='pay')),
    path('', TemplateView.as_view(template_name='home.html'), name='home'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/users/models.py
from django.contrib.auth.base_user import BaseUserManager, AbstractBaseUser
from django.contrib.auth.models import PermissionsMixin
from django.utils.translation import gettext_lazy as _
from apps.utils.random_stuff import *
from django.db import models
# from django.db.models.signals import post_save
# from django.dispatch import receiver
# from ..utils.random_stuff import invite_new_user_email


# Create your models here.
class GPUserManager(BaseUserManager):
    def create_user(self, email, first_name, last_name, password=None, **extra_fields):
        if not email:
            raise ValueError('username is required')

        user = self.model(
            email=email,
            first_name=first_name,
            last_name=last_name,
        )
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, first_name, last_name, password):
        user = self.create_user(email=email, first_name=first_name, last_name=last_name, password=password)
        user.is_superuser = True
        user.is_active = True
        user.is_staff = True
        user.username = user.email
        user.save(using=self._db)
        return user


USER_TYPES = {
    ('SAU', 'Student App User'),
    ('ASU', 'Accounts Office Super User'),
    ('AOU', 'Accounts Office User'),
}


SEX = {
    ('male', 'male'),
    ('female', 'female'),
    ('other', 'other')
}


class GPUser(AbstractBaseUser, PermissionsMixin):
    user_id = models.CharField(unique=True, default=generate_id, editable=False, max_length=5)
    username = models.CharField(
        _('Username'),
        max_length=255,
        blank=True,
        null=True,
    )
    email = models.EmailField(
        _('Email address'),
        unique=True,
    )
    first_name = models.CharField(_('First Name'), max_length=255, blank=True, null=True)
    last_name = models.CharField(_('Last Name'), max_length=255, blank=True, null=True)
    title = models.CharField(_('Title'), max_length=255, blank=True, null=True)
    staff_id = models.CharField(_('Staff Id'), max_length=255, blank=True, null=True)
    user_profile = models.FileField(_('User Profile'), upload_to='media/', blank=True, null=True)
    gender = models.CharField(_('Gender'), choices=SEX, default='other', max_length=255, blank=True, null=True)
    student_id = models.CharField(_('Staff Id'), max_length=255, blank=True, null=True)
    is_active = models.BooleanField(_('Active Status'), default=True)
    is_staff = models.BooleanField(_('Staff Status'), default=False)
    is_superuser = models.BooleanField(_('Super User Status'), default=False)
    date_of_birth = models.DateField(_('Date of Birth'), default=timezone.now)
    login_number = models.IntegerField(_('Login Number'), default=0, blank=True, null=True)
    date_joined = models.DateTimeField(_('Date Joined'), default=timezone.now)
    user_type = models.CharField(_('User Type'), choices=USER_TYPES, max_length=255, default='SAU', blank=True, null=True)

    objects = GPUserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['first_name', 'last_name']

    def get_full_name(self):
        return f'{self.first_name} {self.last_name}'

    def get_short_name(self):
        return self.first_name

    def get_dob(self):
        return self.date_of_birth

    class Meta:
        verbose_name_plural = 'GTUC Pay Users'
        verbose_name = 'user'
        ordering = ('id', 'user_id', 'date_joined')

    def __str__(self):
        return f'{self.email}'


# def invite_user(sender, instance, created, **kwargs):
#     if created and instance.user_type == 'ASU' or instance.user_type == 'AOU':
#         invite_new_user_email(sender, instance.user_id)
#
#
# post_save.connect(invite_user, sender=settings.AUTH_USER_MODEL)

apps/users/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.forms import *

from apps.users.models import GPUser


class LogoutForm(Form):
    pass


class CreateUserForm(UserCreationForm):
    date_of_birth = DateField(widget=TextInput(attrs={'type': 'date'}))

    class Meta(UserCreationForm.Meta):
        model = GPUser
        fields = UserCreationForm.Meta.fields + ('email', 'first_name', 'last_name', 'gender', 'date_of_birth')

apps/users/views.py
from django.contrib.auth import logout, login, authenticate, update_session_auth_hash
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView
from django.http import HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from django.views.generic import *

from apps.pay.models import Payment
from apps.pay_admins.forms import ChangePasswordForm, UserChangeForm
from apps.pay_admins.models import Service
from apps.users.forms import LogoutForm, CreateUserForm
from apps.users.models import GPUser


class Dashboard(LoginRequiredMixin, ListView):
    paginate_by = 5

    def get_template_names(self):
        if self.request.user.user_type == 'ASU' or self.request.user.user_type == 'AOU':
            return 'admins/dashboard.html'
        else:
            return 'users/index.html'

    def get_queryset(self):
        if self.request.user.user_type == 'ASU' or self.request.user.user_type == 'AOU':
            return Payment.objects.all()
        else:
            return Service.objects.all()


class SignUpView(CreateView):
    form_class = CreateUserForm
    template_name = 'users/signup.html'
    success_url = reverse_lazy('users:login')

    def form_valid(self, form):
        valid = super().form_valid(form)
        password, email = form.cleaned_data.get('password1'), form.cleaned_data.get('email')
        form.instance.username = f'{email}'
        form.save()
        return valid


class LogoutView(LoginRequiredMixin, FormView):
    form_class = LogoutForm

    def get_template_names(self):
        if self.request.user.user_type == 'ASU' or self.request.user.user_type == 'AOU':
            return 'users/logout_admin.html'
        else:
            return 'users/logout.html'

    def form_valid(self, form):
        logout(self.request)
        return HttpResponseRedirect(reverse('home'))


class Profile(LoginRequiredMixin, UpdateView):
    model = GPUser
    form_class = UserChangeForm
    pk_url_kwarg = 'id'
    success_url = reverse_lazy('users:dashboard')

    def get_template_names(self):
        if self.request.user.user_type == 'ASU' or self.request.user.user_type == 'AOU':
            return 'users/profile1.html'

        else:
            return 'users/profile.html'


class ChangePassword(LoginRequiredMixin, FormView):
    form_class = ChangePasswordForm
    success_url = reverse_lazy('users:dashboard')

    def get_template_names(self):
        if self.request.user.user_type == 'ASU' or self.request.user.user_type == 'AOU':
            return 'registration/password_change_form1.html'
        else:
            return 'registration/password_change_form.html'

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs

    def form_valid(self, form):
        form.save()
        update_session_auth_hash(self.request, form.user)
        return super().form_valid(form)

templates/users/_forms.html
{% load bootstrap3 %}
<form action="{% url 'admins:create' %}" method="post">
    {% csrf_token %}
    <span class="text-muted">{% bootstrap_form form %}</span>
    <input type="submit" class="btn btn-dark" value="Create">
</form>

templates/users/index.html
{% extends 'layout.html' %}
{% load static from staticfiles %}
{% block header %}GTUC Pay{% endblock %}
{% block content %}
    <div class="row">
        {% if object_list %}
            {% for service in object_list %}
                <div class="col-sm-5 col-lg-3 col=md-3">
                    <a href="{% url 'pay:service-detail' service.id %}">
                        <div class="card">
                            <div class="stat-widget-one">
                                {% if service.logo %}
                                    <div align="center"><img src="{{ service.logo.url }}" height="140" width="150" border="1" /> </div>
                                {% else %}
                                    <div align="center"><img src="{% static 'images/default.png' %}" height="140" width="150" border="1" /> </div>
                                {% endif %}
                                <div align="center">
                                    <div class="stat-digit" style="font-size: 17px;">Pay {{ service.service_name }}</div>
                                </div>
                            </div>
                        </div>
                    </a>
                </div>
            {% endfor %}
        {% endif %}
    </div>
{% endblock %}

templates/users/logout.html
{% extends 'layout.html' %}
{% block title %}Logout? | {{ block.super }}{% endblock %}
{% block content %}
    <div class="container pt">
        <div class="row">
            <div class="col-md-6">
                <h3>Logout?</h3>
                <form method="post">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <p>Are you sure you want to logout?</p>
                    <button type="submit" class="btn btn-deeporange">Logout</button>
                </form>
            </div>
            <div class="col-md-6">
                <h3>Come back soon!</h3>
                <p>Good work today!
            </div>
        </div>
    </div>
{% endblock %}

templates/users/logout_admin.html
{% extends 'admin_layout.html' %}
{% block title %}Logout? | {{ block.super }}{% endblock %}
{% block content %}
    <div class="container pt">
        <div class="row">
            <div class="col-md-6">
                <h3>Logout?</h3>
                <form method="post">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <p>Are you sure you want to logout?</p>
                    <button type="submit" class="btn btn-deeporange">Logout</button>
                </form>
            </div>
            <div class="col-md-6">
                <h3>Come back soon!</h3>
                <p>Good work today!
            </div>
        </div>
    </div>
{% endblock %}

templates/users/payment_list.html
{% for payment in object_list %}
    {{ payment }}
    {% if not payment.is_verified %}
        <a href="{% url 'admins:payment-verify' payment.token 'verified' %}">Verify</a>
    {% endif %}
{% endfor %}

templates/users/profile.html
{% extends 'layout.html' %}
{% load static from staticfiles %}
{% block title %}{{ object.get_full_name }}'s Profile | {{ block.super }}{% endblock %}
{% block content %}
    <div class="row">
            <div class="col-lg-12">
              <div class="card">
                <div class="card-body">
                  <div class="user-profile">
                    <div class="row">
                      <div class="col-lg-4">
                        <div class="user-photo m-b-30">
                          <img class="img-fluid" src="{% if not object.user_profile %}{% static 'images/Picture1.png' %}{% else %}{{ object.user_profile.url }}{% endif %}" style="border-radius: 10px" alt="" />
                        </div>
                      </div>
                      <div class="col-lg-8">
                        <div class="user-profile-name">{{ object.get_full_name }}</div>
                        <div class="row">
                            <div class="col-lg-6">
                                {% if object.is_superuser %}<i class="ti-key"></i>  Super User {% endif %}
                            </div>
                             <div class="col-lg-6" align="right">
                                <a href="{% url 'users:password' %}" class="btn btn-dark"><span class="ti ti-key"></span>&nbsp; Password Reset</a>
                            </div>

                        </div>
                        <div class="user-job-title">{{ object.get_user_type_display }}</div>
                        <div class="custom-tab user-profile-tab">
                          <ul class="nav nav-tabs" role="tablist">
                            <li role="presentation" class="active">
                              <a href="#1" aria-controls="1" role="tab" data-toggle="tab">Edit Profile</a>
                            </li>
                          </ul>
                          <div class="tab-content">
                            <div role="tabpanel" class="tab-pane active" id="1">
                              <div class="contact-information">
                                <form action="{% url 'admins:profile' object.id %}" method="post" enctype='multipart/form-data'>
                                    {% csrf_token %}
                                    <div class="form-group">
                                      <label class="contact-title">First Name:</label>
                                      <input type="text" class="form-control input-rounded" name="{{ form.first_name.name }}" value="{{ form.first_name.value }}" />
                                    </div>
                                    <div class="form-group">
                                      <label class="contact-title">Last Name:</label>
                                      <input type="text" class="form-control input-rounded" name="{{ form.last_name.name }}" value="{{ form.last_name.value }}" />
                                    </div>
                                    <div class="form-group">
                                      <label class="contact-title">Email Address:</label>
                                      <input type="email" class="form-control input-rounded" name="{{ form.email.name }}" value="{{ form.email.value }}" />
                                    </div>
                                    <div class="form-group">
                                      <label class="contact-title">Date of Birth:</label>
                                      <input type="date" class="form-control input-rounded vDateField" name="{{ form.date_of_birth.name }}" value="{{ form.date_of_birth.value }}" />
                                    </div>
                                    <div class="form-group">
                                        <label class="contact-title">Gender:</label>
                                        <select class="form-control input-rounded" name="{{ form.gender.name }}">
                                              {% for x,y in form.fields.gender.choices %}
                                                <option value="{{ x }}" {% if form.gender.value == x %} selected {% endif %}>{{ y }}</option>
                                              {% endfor %}
                                        </select>
                                    </div>
                                    <div class="form-group">
                                      <label class="contact-title">Profile Picture:</label>
                                      <input type="file" name="{{ form.user_profile.name }}" value="{{ form.user_profile.url }}" />
                                    </div>
                                    <input type="submit" class="btn btn-success" value="Save">
                                </form>
                              </div>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
{% endblock %}

templates/users/profile1.html
{% extends 'admin_layout.html' %}
{% load static from staticfiles %}
{% block title %}{{ object.get_full_name }}'s Profile | {{ block.super }}{% endblock %}
{% block content %}
    <div class="row">
            <div class="col-lg-12">
              <div class="card">
                <div class="card-body">
                  <div class="user-profile">
                    <div class="row">
                      <div class="col-lg-4">
                        <div class="user-photo m-b-30">
                          <img class="img-fluid" src="{% if not object.user_profile %}{% static 'images/Picture1.png' %}{% else %}{{ object.user_profile.url }}{% endif %}" style="border-radius: 10px" alt="" />
                        </div>
                      </div>
                      <div class="col-lg-8">
                        <div class="user-profile-name">{{ object.get_full_name }}</div>
                        <div class="row">
                            <div class="col-lg-6">
                                {% if object.is_superuser %}<i class="ti-key"></i>  Super User {% endif %}
                            </div>
                             <div class="col-lg-6" align="right">
                                <a href="{% url 'users:password' %}" class="btn btn-dark"><span class="ti ti-key"></span>&nbsp; Password Reset</a>
                            </div>

                        </div>
                        <div class="user-job-title">{{ object.get_user_type_display }}</div>
                        <div class="custom-tab user-profile-tab">
                          <ul class="nav nav-tabs" role="tablist">
                            <li role="presentation" class="active">
                              <a href="#1" aria-controls="1" role="tab" data-toggle="tab">Edit Profile</a>
                            </li>
                          </ul>
                          <div class="tab-content">
                            <div role="tabpanel" class="tab-pane active" id="1">
                              <div class="contact-information">
                                <form action="{% url 'admins:profile' object.id %}" method="post" enctype='multipart/form-data'>
                                    {% csrf_token %}
                                    <div class="form-group">
                                      <label class="contact-title">First Name:</label>
                                      <input type="text" class="form-control input-rounded" name="{{ form.first_name.name }}" value="{{ form.first_name.value }}" />
                                    </div>
                                    <div class="form-group">
                                      <label class="contact-title">Last Name:</label>
                                      <input type="text" class="form-control input-rounded" name="{{ form.last_name.name }}" value="{{ form.last_name.value }}" />
                                    </div>
                                    <div class="form-group">
                                      <label class="contact-title">Email Address:</label>
                                      <input type="email" class="form-control input-rounded" name="{{ form.email.name }}" value="{{ form.email.value }}" />
                                    </div>
                                    <div class="form-group">
                                      <label class="contact-title">Date of Birth:</label>
                                      <input type="date" class="form-control input-rounded vDateField" name="{{ form.date_of_birth.name }}" value="{{ form.date_of_birth.value }}" />
                                    </div>
                                    <div class="form-group">
                                        <label class="contact-title">Gender:</label>
                                        <select class="form-control input-rounded" name="{{ form.gender.name }}">
                                              {% for x,y in form.fields.gender.choices %}
                                                <option value="{{ x }}" {% if form.gender.value == x %} selected {% endif %}>{{ y }}</option>
                                              {% endfor %}
                                        </select>
                                    </div>
                                    <div class="form-group">
                                      <label class="contact-title">Profile Picture:</label>
                                      <input type="file" name="{{ form.user_profile.name }}" value="{{ form.user_profile.url }}" />
                                    </div>
                                    <input type="submit" class="btn btn-success" value="Save">
                                </form>
                              </div>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
{% endblock %}

templates/users/signup.html
{% extends 'registration/login.html' %}
{% load static from staticfiles %}
{% block image %}
    <div class="col-lg-8 styleName" ><img src="{% static 'images/signup.jpg' %}" width="700" height="900" style="border-radius: 10px" /> </div>
{% endblock %}
{% block header %}Signup{% endblock %}
{% block desc %} Signup to enjoy paying for university fees easily {% endblock %}
{% block action %}"{% url 'users:signup' %}"{% endblock %}
{% block btn %}Signup{% endblock %}
{% block f_style %}style="margin-top: 20px"{% endblock %}
{% block col_m %}style="margin-left: 0"{% endblock %}
{% block ed %}style="margin-top: 20px"{% endblock %}
{% block ed_t %}Already have an account? <a href="{% url 'users:login' %}">Login!</a> {% endblock %}
{% block title %}Signup{% endblock %}
{% block form %}
{#    <div class="form-group">#}
{#        <div class="input-field">#}
{#            <label for="email">Email Address</label>#}
{#            <input type="email" name="{{ form.email.name }}" required class="form-control input-rounded">#}
{#        </div>#}
{#    </div>#}
{#    <div class="form-group">#}
{#        <div class="input-field">#}
{#            <label for="first_name">First Name</label>#}
{#            <input type="text" name="{{ form.first_name.name }}" required class="form-control input-rounded">#}
{#        </div>#}
{#    </div>#}
{#    <div class="form-group">#}
{#        <div class="input-field">#}
{#            <label for="last_name">Last Name</label>#}
{#            <input type="text" name="{{ form.last_name.name }}" required class="form-control input-rounded">#}
{#        </div>#}
{#    </div>#}
{#    <div class="form-group">#}
{#        <div class="input-field">#}
{#            <label for="last_name">Gender</label>#}
{#            <select class="form-control input-rounded" required name="{{ form.gender.name }}">#}
{#                {% for x,y in form.fields.gender.choices %}#}
{#                    <option value="{{ x }}">{{ y }}</option>#}
{#                {% endfor %}#}
{#            </select>#}
{#        </div>#}
{#    </div>#}
{#    <div class="form-group">#}
{#        <div class="input-field">#}
{#            <label for="date_of_birth">Date of Birth</label>#}
{#            <input type="date" name="{{ form.date_of_birth.name }}" required class="form-control input-rounded">#}
{#        </div>#}
{#    </div>#}
{#    <div class="form-group">#}
{#        <div class="input-field">#}
{#            <label for="date_of_birth">Password</label>#}
{#            <input type="password" name="{{ form.password1.name }}" required class="form-control input-rounded">#}
{#        </div>#}
{#    </div>#}
{#    <div class="form-group">#}
{#        <div class="input-field">#}
{#            <label for="date_of_birth">Password Again</label>#}
{#            <input type="password" name="{{ form.password2.name }}" required class="form-control input-rounded">#}
{#        </div>#}
{#    </div>#}
{#    {% if form.non_field_errors %}#}
{#        <ul class='form-errors'>#}
{#            {% for error in form.non_field_errors %}#}
{#                <li><span class="dz-error-message text-danger">{{ error }}</span></li>#}
{#            {% endfor %}#}
{#        </ul>#}
{#    {% endif %}#}
{% endblock %}