apps/pay/urls.py
from django.urls import *
from .views import *

app_name = 'pay'


urlpatterns = [
    path('service/detail/<id>/', ServiceDetail.as_view(), name='service-detail'),
    path('momo/<id>/', PayMomo.as_view(), name='pay-momo'),
    path('card/<id>/', PayCard.as_view(), name='pay-card'),
    path('momo/confirm/<id>/', ConfirmMomoPay.as_view(), name='confirm-momo'),
    path('card/confirm/<id>/', ConfirmCardPay.as_view(), name='confirm-card'),
    path('cancel/<id>/', CancelPayment.as_view(), name='cancel'),
    path('success/<id>/', SuccessPayment.as_view(), name='success'),
    path('transactions/', UserPayment.as_view(), name='transactions'),
    path('transaction/detail/<id>/', PaymentDetail.as_view(), name='transaction-detail'),
    path('support/', Support.as_view(), name='support'),
]

apps/users/urls.py
from django.urls import path, include
from django.views.generic import TemplateView

from apps.users.views import *

app_name = 'users'


urlpatterns = [
    path('dashboard/', Dashboard.as_view(), name='dashboard'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('signup/', SignUpView.as_view(), name='signup'),
    # path('layout/admin/', TemplateView.as_view(template_name='admin_layout.html')),
    path('password/', ChangePassword.as_view(), name='password'),
    path('profile/<id>', Profile.as_view(), name='profile'),
    path('', include('django.contrib.auth.urls')),



]

gtuc_pay_api/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

from apps.pay_admins import urls as admin_urls
from apps.users import urls as user_urls
from gtuc_pay_api import settings
from apps.pay import urls as pay_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('admins/', include(admin_urls, namespace='admins')),
    path('users/', include(user_urls, namespace='users')),
    path('pay/', include(pay_urls, namespace='pay')),
    path('', TemplateView.as_view(template_name='home.html'), name='home'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/pay/models.py
from django.db import models

from apps.pay_admins.models import Service, Faculty
from apps.utils.random_stuff import *
from django.conf import settings
# # Create your models here.


DEBIT_TYPES = {
    ('MTN', 'MTN Mobile Money'),
    ('Voda', 'Vodafone Cash'),
    ('Tigo', 'Tigo Cash'),
    ('Air', 'Airtel Money'),
}

PROGRAMMES = {
    ('BIT', 'Bsc. Information Technology'),
    ('BCE', 'Bsc. Computer Engineering'),
    ('BTE', 'Bsc. Telecommunication Engineering'),
    ('BF', 'Bsc. Banking & Financial'),
    ('BM', 'Bsc. Management'),
    ('BA', 'Bsc. Accounting'),
    ('BMk', 'Bsc. Marketing'),
    ('BE', 'Bsc. Economics'),
    ('BHR', 'Bsc. Human Resource Management'),
    ('BAC', 'Bsc. Accounting with Computing'),
    ('BPL', 'Bsc. Procurement and Logistics'),

}

LEVEL = {
    ('100', '100'),
    ('200', '200'),
    ('300', '300'),
    ('400', '400'),
}


class Payment(models.Model):
    student_full_name = models.CharField(max_length=255, blank=True, null=True)
    # student_index_number = models.CharField(max_length=255, blank=True, null=True)
    student_faculty = models.ForeignKey(Faculty, related_name='payments', on_delete=models.SET_NULL, blank=True,
                                        null=True)
    student_programme = models.CharField(choices=PROGRAMMES, blank=True, null=True, max_length=255,)
    level = models.CharField(choices=LEVEL, blank=True, null=True, max_length=255,)
    service_to_pay = models.ForeignKey(Service, related_name='services', on_delete=models.SET_NULL, blank=True,
                                       null=True)
    amount = models.DecimalField(max_digits=8, decimal_places=2, blank=True, null=True)
    balance = models.CharField(max_length=255, blank=True, null=True)
    student_id = models.CharField(
        max_length=255,
        help_text='Enter the student ID of the student you are paying fees for',
        blank=True,
        null=True
    )
    pay_with = models.CharField(choices=DEBIT_TYPES, max_length=255, blank=True, null=True)
    is_card = models.BooleanField(default=False)
    card_number = models.CharField(max_length=255, blank=True, null=True)
    cvv = models.IntegerField(blank=True, null=True)
    expiry_date = models.DateField(blank=True, null=True)
    mobile_number = models.CharField(max_length=255, blank=True, null=True)
    paid_at = models.DateTimeField(default=timezone.now)
    paid_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        related_name='dues_fees',
        on_delete=models.SET_NULL,
        blank=True,
        null=True
    )
    token = models.CharField(default=unique_token, max_length=255, unique=True)
    is_verified = models.BooleanField(default=False)

    def __str__(self):
        return f'{self.student_full_name}, {self.amount}'

    class Meta:
        ordering = ['-paid_at']


#
#
#
# class Accounts(models.Model):
#     account_name = models.CharField(max_length=255, blank=True, null=True)
#     account_number = models.CharField(max_length=255, blank=True, null=True)
#     bank = models.CharField(max_length=255, blank=True, null=True)
#
#     class Meta:
#         abstract = True
#
#
# class Association(models.Model):
#     name = models.CharField(max_length=255, blank=True, null=True)
#     faculty = models.ForeignKey(
#         Faculty,
#         related_name='association_faculty',
#         on_delete=models.SET_NULL,
#         blank=True,
#         null=True
#     )
#     logo = models.FileField(upload_to='media/', blank=True, null=True)
#     created_at = models.DateTimeField(default=timezone.now)
#     created_by = models.ForeignKey(
#         settings.AUTH_USER_MODEL,
#         related_name='association',
#         on_delete=models.SET_NULL,
#         blank=True,
#         null=True
#     )
#
#     def __str__(self):
#         return f'{self.name}'
#
#
# class SchoolAccounts(Accounts):
#     fees = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
#
#
# class AssociationAccounts(Accounts):
#     fees = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
#
#

#
#
# class PayFees(models.Model):
#     token = models.CharField(max_length=255, blank=True, null=True)
#     student_id = models.CharField(
#         max_length=255,
#         help_text='Enter the student ID of the student you are paying fees for',
#         blank=True,
#         null=True
#     )
#     fees_account = models.ForeignKey(
#         SchoolAccounts,
#         related_name='fees_accounts',
#         on_delete=models.SET_NULL,
#         blank=True,
#         null=True
#     )
#     amount = models.DecimalField(max_digits=15, decimal_places=2)
#     debit_account_type = models.CharField(choices=DEBIT_TYPES, max_length=255, blank=True, null=True)
#     card_number = models.CharField(max_length=255, blank=True, null=True)
#     cvv = models.IntegerField(blank=True, null=True)
#     expiry_date = models.DateField()
#     mobile_number = models.CharField(max_length=255, blank=True, null=True)
#     paid_at = models.DateTimeField(default=timezone.now)
#     paid_by = models.ForeignKey(
#         settings.AUTH_USER_MODEL,
#         related_name='pay_fees',
#         on_delete=models.SET_NULL,
#         blank=True,
#         null=True
#     )
#
#
# class DuesPayments(models.Model):
#     token = models.CharField(max_length=255, blank=True, null=True)
#     association = models.ForeignKey(
#         Association,
#         related_name='association',
#         on_delete=models.SET_NULL,
#         blank=True,
#         null=True
#     )
#     student_id = models.CharField(
#         max_length=255,
#         help_text='Enter the student ID of the student you are paying fees for',
#         blank=True,
#         null=True
#     )
#     fees_account = models.ForeignKey(
#         SchoolAccounts,
#         related_name='dues_accounts',
#         on_delete=models.SET_NULL,
#         blank=True,
#         null=True
#     )
#     amount = models.DecimalField(max_digits=15, decimal_places=2)
#     debit_account_type = models.CharField(choices=DEBIT_TYPES, max_length=255, blank=True, null=True)
#     card_number = models.CharField(max_length=255, blank=True, null=True)
#     cvv = models.IntegerField(blank=True, null=True)
#     expiry_date = models.DateField()
#     mobile_number = models.CharField(max_length=255, blank=True, null=True)
#     paid_at = models.DateTimeField(default=timezone.now)
#     paid_by = models.ForeignKey(
#         settings.AUTH_USER_MODEL,
#         related_name='dues_fees',
#         on_delete=models.SET_NULL,
#         blank=True,
#         null=True
#     )
#
#
# class Complaint(models.Model):
#     from_user = models.ForeignKey(
#         settings.AUTH_USER_MODEL,
#         related_name='from_users',
#         on_delete=models.SET_NULL,
#         blank=True,
#         null=True
#     )
#     subject = models.CharField(max_length=255, blank=True, null=True)
#     message = models.TextField(max_length=400, null=True, blank=True)
#     shots = models.FileField(upload_to='media/', blank=True, null=True)
#     complaint_date = models.DateTimeField(default=timezone.now)
#
#     def __str__(self):
#         return f'{self.from_user}, {self.subject}'
#
#     class Meta:
#         verbose_name_plural = 'Complaints'
#

templates/payment/_momo.html
<form action="#" method="post">
    {% csrf_token %}
    {{ object }}
    <div class="form-group">
      <label class="contact-title">Student Full Name:</label>
      <input type="text" class="form-control input-rounded" name="{{ form.student_full_name.name }}" required />
    </div>
    <div class="form-group">
      <label class="contact-title">Student ID:</label>
      <input type="text" class="form-control input-rounded" name="{{ form.student_id.name }}" required />
    </div>
    <div class="form-group">
      <label class="contact-title">Student Level:</label>
      <select class="form-control input-rounded" name="{{ form.level.name }}">
          {% for x,y in form.fields.level.choices %}
            <option value="{{ x }}">{{ y }}</option>
          {% endfor %}
      </select>
    </div>
    <div class="form-group">
      <label class="contact-title">Student Programme of Study:</label>
      <select class="form-control input-rounded" name="{{ form.student_programme.name }}">
          {% for x,y in form.fields.student_programme.choices %}
            <option value="{{ x }}">{{ y }}</option>
          {% endfor %}
      </select>
    </div>
    <div class="form-group">
      <label class="contact-title">Student Faculty:</label>
      <select class="form-control input-rounded" name="{{ form.student_faculty.name }}">
          {% for x,y in form.fields.student_faculty.choices %}
            <option value="{{ x }}">{{ y }}</option>
          {% endfor %}
      </select>
    </div>
    <div class="form-group">
      <label class="contact-title">Payment Option:</label>
      <select class="form-control input-rounded" name="{{ form.pay_with.name }}">
          <option>Vodafone Cash</option>
          <option>Tigo Cash</option>
          <option>MTN Money</option>
          <option>Airtel Money</option>
      </select>
    </div>
    <div class="form-group">
      <label class="contact-title">Mobile Number:</label>
      <input type="text" class="form-control input-rounded" name="{{ form.mobile_number.name }}" />
    </div>
    <div class="form-group">
      <label class="contact-title">Service to pay:</label>
      <input type="text" class="form-control input-rounded" name="{{ form.service_to_pay.name }}" value="{{ service.service_name }}" placeholder="{{ object.service_name.value }}" />
    </div>
</form>

{{ form }}

templates/payment/edit_card.html
{% extends 'layout.html' %}
{% block title %}
    Confirm your payment!
{% endblock %}
{% block header %} Confirm Payment for {{ object.service_to_pay.service_name }}{% endblock %}
{% block content %}
    <div class="row">
        <div class="col-lg-8 col-md-8 col-sm-12" style="margin-left: 5%; margin-right: 5%">
            <div class="card">
                <div class="card-body">
                    <form action="" method="post">
                        {% csrf_token %}
                        <div class="form-group">
                            <label for="student_full_name" class="text-muted">Student Full Name</label>
                            <input type="text" name="{{ form.student_full_name.name }}" value="{{ form.student_full_name.value }}" class="form-control input-rounded" />
                        </div>
                        <div class="form-group">
                            <label for="student_id" class="text-muted">Student Index Number 1</label>
                            <input type="text" name="{{ form.student_id.name }}" value="{{ form.student_id.value }}" class="form-control input-rounded" placeholder="Please enter the index number the student you are paying for" />
                        </div>
                        <div class="form-group">
                          <label for="level">Student Level:</label>
                          <select class="form-control input-rounded" name="{{ form.level.name }}">
                              {% for x,y in form.fields.level.choices %}
                                <option value="{{ x }}" {% if form.level.value == x %} selected {% endif %}>{{ y }}</option>
                              {% endfor %}
                          </select>
                        </div>
                        <div class="form-group">
                          <label for="student_programme">Student Programme of Study:</label>
                          <select class="form-control input-rounded" name="{{ form.student_programme.name }}">
                              {% for x,y in form.fields.student_programme.choices %}
                                <option value="{{ x }}" {% if form.student_programme.value == x %} selected {% endif %}>{{ y }}</option>
                              {% endfor %}
                          </select>
                        </div>
                        <div class="form-group">
                            <label for="student_faculty" class="text-muted">Student Faculty</label>
                            <select class="form-control input-rounded" name="{{ form.student_faculty.name }}">
                                  {% for x,y in form.fields.student_faculty.choices %}
                                    <option value="{{ x }}" {% if form.student_faculty.value == x %} selected {% endif %}>{{ y }}</option>
                                  {% endfor %}
                            </select>
                        </div>
                        <div class="form-group">
                            <label class="text-muted">Amount</label>
                            <input type="number" name="{{ form.amount.name }}" value="{{ form.amount.value }}" class="form-control input-rounded" placeholder="Please enter the amount you are paying" />
                        </div>
                        <div class="form-group">
                          <label class="contact-title">Card Number</label>
                            <input type="text" name="{{ form.card_number.name }}" value="{{ form.card_number.value }}" class="form-control input-rounded" placeholder="Please enter the card number" />
                        </div>
                        <div class="form-group">
                          <label class="contact-title">CVV</label>
                          <input type="text" class="form-control input-rounded" value="{{ form.cvv.value }}" name="{{ form.cvv.name }}" placeholder="Enter the mobile money number" />
                        </div>
                        <div class="form-group">
                          <label class="contact-title">Expiry Date:</label>
                            {{ form.expiry_date }}
                        </div>

{#                                {{ form.as_p }}#}
                        {% if form.non_field_errors %}
                            <ul class='form-errors'>
                                {% for error in form.non_field_errors %}
                                    <li><span class="dz-error-message text-danger">{{ error }}</span></li>
                                {% endfor %}
                            </ul>
                        {% endif %}
                        <div class="text-muted text-primary"><i>After clicking on confirm, a token would be sent to your email for verification!</i></div>
                        <div class="row">
                            <div class="col-lg-3 col-md-3 col-sm-3">
                                <input type="submit" class="btn btn-success" value="Confirm Payment">
                    </form>
                            </div>
                <div class="col-lg-3 col-md-3 col-sm-3">
                    <form method="post" action="{% url 'pay:cancel' object.id %}">
                        {% csrf_token %}
                        <input type="submit" class="btn btn-danger" value="Cancel">
                    </form>
                </div>
                        </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/payment/edit_momo.html
{% extends 'layout.html' %}
{% block title %}
    Confirm your payment!
{% endblock %}
{% block header %}Confirm your payment!{% endblock %}
{% block content %}
    <div class="row">
        <div class="col-lg-8 col-md-8 col-sm-12" style="margin-left: 5%; margin-right: 5%">
            <div class="card">
                <div class="card-body">
                    <form action="" method="post">
                        {% csrf_token %}
                        <div class="form-group">
                            <label for="student_full_name" class="text-muted">Student Full Name</label>
                            <input type="text" name="{{ form.student_full_name.name }}" value="{{ form.student_full_name.value }}" class="form-control input-rounded" />
                        </div>
                        <div class="form-group">
                            <label for="student_id" class="text-muted">Student Index Number</label>
                            <input type="text" name="{{ form.student_id.name }}" value="{{ form.student_id.value }}" class="form-control input-rounded" placeholder="Please enter the index number the student you are paying for" />
                        </div>
                        <div class="form-group">
                          <label for="level">Student Level:</label>
                          <select class="form-control input-rounded" name="{{ form.level.name }}">
                              {% for x,y in form.fields.level.choices %}
                                <option value="{{ x }}" {% if form.level.value == x %} selected {% endif %}>{{ y }}</option>
                              {% endfor %}
                          </select>
                        </div>
                        <div class="form-group">
                          <label for="student_programme">Student Programme of Study:</label>
                          <select class="form-control input-rounded" name="{{ form.student_programme.name }}">
                              {% for x,y in form.fields.student_programme.choices %}
                                <option value="{{ x }}" {% if form.student_programme.value == x %} selected {% endif %}>{{ y }}</option>
                              {% endfor %}
                          </select>
                        </div>
                        <div class="form-group">
                            <label for="student_faculty" class="text-muted">Student Faculty</label>
                            <select class="form-control input-rounded" name="{{ form.student_faculty.name }}">
                                  {% for x,y in form.fields.student_faculty.choices %}
                                    <option value="{{ x }}" {% if form.student_faculty.value == x %} selected {% endif %}>{{ y }}</option>
                                  {% endfor %}
                            </select>
                        </div>
                        <div class="form-group">
                            <label class="text-muted">Amount</label>
                            <input type="number" name="{{ form.amount.name }}" value="{{ form.amount.value }}" class="form-control input-rounded" placeholder="Please enter the amount you are paying" />
                        </div>
                        <div class="form-group">
                          <label class="contact-title">Payment Option:</label>
                            <select class="form-control input-rounded" name="{{ form.pay_with.name }}">
                                  {% for x,y in form.fields.pay_with.choices %}
                                    <option value="{{ x }}" {% if form.pay_with.value == x %} selected {% endif %}>{{ y }}</option>
                                  {% endfor %}
                            </select>
                        </div>
                        <div class="form-group">
                          <label class="contact-title">Mobile Number:</label>
                          <input type="text" class="form-control input-rounded" value="{{ form.mobile_number.value }}" name="{{ form.mobile_number.name }}" placeholder="Enter the mobile money number" />
                        </div>
{#                                {{ form.as_p }}#}
                        {% if form.non_field_errors %}
                            <ul class='form-errors'>
                                {% for error in form.non_field_errors %}
                                    <li><span class="dz-error-message text-danger">{{ error }}</span></li>
                                {% endfor %}
                            </ul>
                        {% endif %}
                        <div class="text-muted text-primary"><i>After clicking on confirm, a token would be sent to your email for verification!</i></div>
                        <div class="row">
                            <div class="col-lg-3 col-md-3 col-sm-3">
                                <input type="submit" class="btn btn-success" value="Confirm Payment">
                    </form>
                            </div>
                <div class="col-lg-3 col-md-3 col-sm-3">
                    <form method="post" action="{% url 'pay:cancel' object.id %}">
                        {% csrf_token %}
                        <input type="submit" class="btn btn-danger" value="Cancel">
                    </form>
                </div>
                        </div>


                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/payment/service_detail.html
{% extends 'layout.html' %}
{% load static from staticfiles %}
{% load pay_tags %}
{% block header %}{{ object.service_name }} Details {% endblock %}
{% block content %}
    <div class="row">
        <div class="col-lg-12">
          <div class="card">
            <div class="card-body">
              <div class="user-profile">
                <div class="row">
                  <div class="col-lg-6 styleName">
                    <div class="user-photo m-b-30">
                      <img class="img-fluid" src="{% if object.logo %}{{ object.logo.url }}{% else %}{% static 'images/user-profile.jpg' %}{% endif %}" width="300" height="300" style="border-radius: 10px" alt="" />
                    </div>
                    <div class="user-work">
                      <h4>Details</h4>
                      <div class="work-content">
                        <h3>{{ object.service_name }} </h3>
                        <p>{{ object.currency }} {{ object.amount }}</p>
                      </div>
                    </div>
                    <div class="user-work">
                      <h4>Bank Details</h4>
                      <div class="work-content">
                        <h3>{{ object.bank_name }} </h3>
                        <p>{{ object.account_number }}</p>

                      </div>
                    </div>
                  </div>
                  <div class="col-lg-6">
                      <div class="user-profile-name styleName"><i>Pay with your popular payment choices</i></div>
                      <div class="row styleName">
                          <div class="col-md-3 col-sm-3"><img src="{% static 'images/mtnlogo.jpg' %}" height="80" width="100"></div>
                          <div class="col-md-3 col-sm-3"><img src="{% static 'images/airtellogo.jpg' %}" height="80" width="100"></div>
                          <div class="col-md-3 col-sm-3"><img src="{% static 'images/tigologo.png' %}" height="80" width="100"></div>
                          <div class="col-md-3 col-sm-3"><img src="{% static 'images/card.png' %}" height="80" width="100"></div>
                      </div>
                    <div class="custom-tab user-profile-tab">
                          <ul class="nav nav-tabs" role="tablist">
                            <li role="presentation" class="active">
                              <a href="#1" aria-controls="1" role="tab" data-toggle="tab">Select Payment Option</a>
                            </li>
                          </ul>
                        <br>
                        <a href="{% url 'pay:pay-momo' object.id %}" class="card col-lg-5 col-sm-5 col-md-5"><img src="{% static 'images/mobile_money.jpg' %}" title="Pay with your MTN, Vodafone, Airtel and Tigo mobile money account" width="200" height="150" style="border-radius: 20px;" /> </a>
                        <a href="{% url 'pay:pay-card' object.id %}" class="card col-lg-5 col-sm-5 col-md-5"><img src="{% static 'images/card.png' %}" title="Pay with your Visa and MasterCard" width="200" height="150" style="border-radius: 20px" /> </a>
{#                          <div class="dropdown">#}
{#                            <button class="btn btn-primary dropdown-toggle" type="button" data-toggle="dropdown">Select Payment#}
{#                                <span class="caret"></span></button>#}
{#                            <ul class="dropdown-menu">#}
{#                                <li><a href="{% url 'pay:pay-momo' object.id %}">Mobile Money</a></li>#}
{#                                <li><a href="#">Card Payment</a></li>#}
{##}
{#                            </ul>#}
{#                        </div>#}
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
{% endblock %}

templates/payment/success.html
{% extends 'layout.html' %}
{% block header %}Payment Completed{% endblock %}
{% block content %}
    <div class="row text-center">
        <div class="col-sm-12 col-sm-offset-3">
        <br><br> <h2 style="color:#0fad00">Success</h2>
        <img src="{{ object.service_to_pay.logo.url }}">
        <h3>Hi, {{ object.paid_by.get_full_name }}</h3>
            <p style="font-size:20px;color:#5C5C5C;">Your payment for {{ object.service_to_pay.service_name }} at <strong>{{ object.service_to_pay.currency }} {{ object.amount }} </strong>was successful.<br> A token has been sent to your account email address.<br>
            Thank you for using GTUC Pay!
            </p>
        <a href="{% url 'users:dashboard' %}" class="btn btn-dark">     Back to Dashboard      </a>
    <br><br>
        </div>

	</div>

{% endblock %}

templates/payment/transactions-detail.html
{% extends 'layout.html' %}
{% load static from staticfiles %}
{% load humanize %}
{% block header %}Informal Receipt{% endblock %}
{% block css %}

{% endblock %}
{% block content %}
    <div class="container">
      <div class="card">
        <div class="card-header">
            <div class="row">
                <div class="col-lg-4 col-sm-4" align="left">
                    <img src="{% static 'images/Picture1.png' %}" height="110" width="120">
                </div>
                <div class="col-lg-8 col-sm-5 styleName" align="center" style="margin-left: 15%; position: absolute">
                    <h4>Ghana Technology University College</h4>
                    <span class="text-muted">PMB 100 (ACCRA)</span>
                    <h5>OFFICIAL RECEIPT</h5>

                </div>
            </div>


        </div>
        <div class="card-body">
            <div class="row mb-4">
                <div class="col-lg-6 col-sm-6">

                </div>
                <div class="col-lg-6 col-sm-6" align="right">
                    <div >
                        <strong>Token no: {{ object.token }}</strong>
                    </div>
                    <div>Date: {{ object.paid_at }}</div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-6">
                    <h6><i>Recieved From</i>: {{ object.student_full_name }}</h6>
                </div>
                <div class="col-lg-6">
                    <h6><i>Prog.Level: {{ object.get_student_programme_display }}, {{ object.level }}</i></h6>
                </div>
            </div>
            <hr>
            <div class="row">
                <div class="col-lg-8">
                    <h6><i>The Sum of: {{ object.service_to_pay.currency }} {{ object.amount | apnumber | intcomma }}</i></h6>
                </div>
                <div class="col-lg-4">
                    <h6>Student Reg#: {{ object.student_id }}</h6>
                </div>
            </div>
            <hr>
            <div class="row">
                <div class="col-lg-8">
                    <h6><i>being</i> : {% if object.balance == '0.00' %} Full payment of {% else %} Part payment of {% endif %} {{ object.service_to_pay.service_name }}</h6>
                </div>
                <div class="col-lg-4">
                    <h6>Balance: {{ object.service_to_pay.currency }}{{ object.balance }}</h6>
                </div>
            </div>
            <hr>
        </div>
      </div>
    </div>
{% endblock %}